### PR TITLE
Refactor pushups code

### PR DESCRIPTION
**Pull request by achiu8**
These changes are made on top of the other PR, so review that one first.

### CODE REVIEW

**Comment by achiu8** [comment]
Actually, let me know once you've reviewed and merged the other one.

**Comment by yujinjcho** [comment]
@achiu8 Actually, I was wondering, should a lot of the functions currently in webapp.js be separated into modules?

**Comment by yujinjcho** [comment]
@achiu8 Also, I merged other one

**Comment by achiu8** [comment]
@yujinjcho Mm yeah, probably..

**Comment by achiu8** [comment]
@yujinjcho I changed the target to master since it has the other changes now, so you can merge whenever you think it's good.

**Pull request merged**
